version: '3'

services:
  moodle:
    build: ./moodle
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/site
  moodle-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'moodledb:/var/lib/postgresql'
  moodle-test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'moodletestdb:/var/lib/postgresql'
  moodle-int-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_integration
      POSTGRES_USER: dev_integration
    volumes:
     - 'moodleintdb:/var/lib/postgresql'
volumes:
    moodledb:
    moodletestdb:
    moodleintdb:
